package:
  name: snapt
  version: "0.2"

source:
  git_url: https://github.com/ursky/SnapT.git

requirements:
  build:

  run:
    - stringtie>=1.3.4
    - openssl=1.0*
    - samtools>=1.6
    - hisat2
    - prokka
    - prodigal
    - blast
    - bedtools
    - diamond

about:
  home: https://github.com/ursky/SnapT
  license: MIT
  license_file: LICENSE

