package:
  name: snapt
  version: "0.1.1"

source:
  git_url: https://github.com/ursky/SnapT.git

requirements:
  build:

  run:
    - stringtie>=1.3.4
    - openssl=1.0*
    - samtools
    - hisat2
    - prokka
    - prodigal

about:
  home: https://github.com/ursky/SnapT
  license: MIT
  license_file: LICENSE

