package:
  name: snapt
  version: "0.3"

source:
  git_url: https://github.com/ursky/SnapT.git

requirements:
  build:

  run:
    - bedtools
    - blast
    - diamond
    - hisat2
    - infernal
    - matplotlib
    - openssl=1.0*
    - prokka
    - prodigal
    - samtools>=1.6
    - stringtie>=1.3.4

about:
  home: https://github.com/ursky/SnapT
  license: MIT
  license_file: LICENSE

